/// Extension trait for ABI representation.
///
/// Implemented by types generated by the [`ylm!`] macro when using the [`#[ylm(abi)]`][attr]
/// attribute.
///
/// [`ylm!`]: crate::ylm
/// [attr]: https://docs.rs/base-ylm-macro/latest/base_ylm_macro/macro.sol.html#attributes
pub trait JsonAbiExt {
    /// The ABI representation of this type.
    type Abi;

    /// Returns the ABI representation of this type.
    fn abi() -> Self::Abi;
}
